In [2]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


## 切片、提取、赋值、索引
### 1. 用筛法产生素数判别组：

In [6]:
is_prime = np.ones((100,), dtype=bool)
N_max = int(np.sqrt(len(is_prime)))
for j in range(2, N_max):
    is_prime[2*j::j]=False
(is_prime[17],
is_prime[18])

(True, False)

### 2. Using boolean masks：

In [7]:
np.random.seed(3)
a = np.random.randint(0, 20, 15)
mask = (a % 3 == 0)
extract_from_a = a[mask]
extract_from_a

array([ 3,  0,  9,  6,  0, 12])

In [9]:
a[a % 3 == 0] = -1
a

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, -1,  7, 14, 17])

#### 组合 #1 #2:

In [12]:
a = np.arange(100)
is_prime = np.ones((100,), dtype=bool)
N_max = int(np.sqrt(len(is_prime)))
for j in range(2, N_max):
    is_prime[2*j::j]=False
primes = a[is_prime]
primes

array([ 0,  1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47,
       53, 59, 61, 67, 71, 73, 79, 83, 89, 97])

## 运算
### 1. 按行、列求和

In [14]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [15]:
x.sum(axis=0)  # 按列求和，即一列列地求和

array([3, 3])

In [16]:
x.sum(axis=1)  # 按行求和，即一行行地求和

array([2, 4])